### ISSUE TITLE
Presence of tox-pip-version and tox-venv causes isolation issues

### ISSUE THREAD

**Issue by jaraco** [pglass/tox-pip-version#20] opened 2019-10-13 21:14 UTC
See tox-dev/tox#1435 for the details, but it seems that by having tox-pip-version installed alongside tox and tox-venv can cause tox to incorrectly provision a Python 2.7 virtualenv and to then use the system Python for installing dependencies and running tests.

**Comment by jaraco** [comment] 2019-10-20 21:22
This issue is a deal-breaker for me. Today I ran `tox -e py27` on one of my projects and it polluted my system site-packages again. I'm going to have to drop use of tox-pip-version until this issue can be fixed.

**Comment by pglass** [comment] 2019-10-22 19:40
Hi, sorry for the delay. I am able to reproduce this.

This is tox-pip-version's fault. Basically, with tox-venv and python 2, tox-venv will "fail" to create the virtualenv (which is expected, since there's no `python2 -m venv`) but tox-pip-version doesn't realize that, so it proceeds without a virtualenv.

I'll get a fix for this released tonight.

**Closed** 2019-10-23 09:36 UTC

**Comment by pglass** [comment] 2019-10-23 09:46
@jaraco I released a fix for this: https://pypi.org/project/tox-pip-version/0.0.6/#history. Let me know if you still see a problem.

**Comment by jaraco** [comment] 2019-10-25 23:32
Confirmed the fix: 

```
draft $ cat > Dockerfile                                                                                                                                                  
FROM jaraco/py37-tox
RUN apt install -y python2.7
RUN python -m venv tox-venv
RUN tox-venv/bin/python -m pip install tox tox-venv tox-pip-version
RUN echo "[tox]\nskipsdist = True\n[testenv]\ncommands = python -V\nskipinstall = True" > tox.ini
RUN tox-venv/bin/tox -e py27
draft $ docker build . --no-cache                                                                                                                                         
Sending build context to Docker daemon  14.85kB
Step 1/6 : FROM jaraco/py37-tox
 ---> da91dc50cea2
Step 2/6 : RUN apt install -y python2.7
 ---> Running in e870154df373

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libpython2.7-minimal libpython2.7-stdlib python2.7-minimal
Suggested packages:
  python2.7-doc binutils binfmt-support
The following NEW packages will be installed:
  libpython2.7-minimal libpython2.7-stdlib python2.7 python2.7-minimal
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 3786 kB of archives.
After this operation, 16.0 MB of additional disk space will be used.
Get:1 http://security.ubuntu.com/ubuntu bionic-security/main amd64 libpython2.7-minimal amd64 2.7.15-4ubuntu4~18.04.2 [336 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security/main amd64 python2.7-minimal amd64 2.7.15-4ubuntu4~18.04.2 [1296 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/main amd64 libpython2.7-stdlib amd64 2.7.15-4ubuntu4~18.04.2 [1916 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/main amd64 python2.7 amd64 2.7.15-4ubuntu4~18.04.2 [239 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 3786 kB in 2s (2132 kB/s)
Selecting previously unselected package libpython2.7-minimal:amd64.
(Reading database ... 15563 files and directories currently installed.)
Preparing to unpack .../libpython2.7-minimal_2.7.15-4ubuntu4~18.04.2_amd64.deb ...
Unpacking libpython2.7-minimal:amd64 (2.7.15-4ubuntu4~18.04.2) ...
Selecting previously unselected package python2.7-minimal.
Preparing to unpack .../python2.7-minimal_2.7.15-4ubuntu4~18.04.2_amd64.deb ...
Unpacking python2.7-minimal (2.7.15-4ubuntu4~18.04.2) ...
Selecting previously unselected package libpython2.7-stdlib:amd64.
Preparing to unpack .../libpython2.7-stdlib_2.7.15-4ubuntu4~18.04.2_amd64.deb ...
Unpacking libpython2.7-stdlib:amd64 (2.7.15-4ubuntu4~18.04.2) ...
Selecting previously unselected package python2.7.
Preparing to unpack .../python2.7_2.7.15-4ubuntu4~18.04.2_amd64.deb ...
Unpacking python2.7 (2.7.15-4ubuntu4~18.04.2) ...
Setting up libpython2.7-minimal:amd64 (2.7.15-4ubuntu4~18.04.2) ...
Setting up libpython2.7-stdlib:amd64 (2.7.15-4ubuntu4~18.04.2) ...
Setting up python2.7-minimal (2.7.15-4ubuntu4~18.04.2) ...
Linking and byte-compiling packages for runtime python2.7...
Setting up python2.7 (2.7.15-4ubuntu4~18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Removing intermediate container e870154df373
 ---> 3d5880fdba5c
Step 3/6 : RUN python -m venv tox-venv
 ---> Running in 68942b4f1236
Removing intermediate container 68942b4f1236
 ---> b1d722a58242
Step 4/6 : RUN tox-venv/bin/python -m pip install tox tox-venv tox-pip-version
 ---> Running in 39e7959e003e
Collecting tox
  Using cached https://files.pythonhosted.org/packages/a7/0c/ed234b83d2c4fcef1cfccf97371183d51dafae62e64334de34d0a6333114/tox-3.14.0-py2.py3-none-any.whl
Collecting tox-venv
  Downloading https://files.pythonhosted.org/packages/11/92/3bf5efd94dcc470b15d351ba77294bb3d7faf221b1c9912c08dff7ce33a5/tox_venv-0.4.0-py2.py3-none-any.whl
Collecting tox-pip-version
  Downloading https://files.pythonhosted.org/packages/94/f3/3e68654797b8c42717ba6ae0e4d163f93995d648b493c8699638e4d8f22c/tox-pip-version-0.0.6.tar.gz
Collecting pluggy<1,>=0.12.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/92/c7/48439f7d5fd6bddb4c04b850bb862b42e3e2b98570040dfaf68aedd8114b/pluggy-0.13.0-py2.py3-none-any.whl
Collecting six<2,>=1.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting importlib-metadata<1,>=0.12; python_version < "3.8" (from tox)
  Using cached https://files.pythonhosted.org/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Collecting py<2,>=1.4.17 (from tox)
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting virtualenv>=14.0.0 (from tox)
  Downloading https://files.pythonhosted.org/packages/c5/97/00dd42a0fc41e9016b23f07ec7f657f636cb672fad9cf72b80f8f65c6a46/virtualenv-16.7.7-py2.py3-none-any.whl (3.4MB)
Collecting filelock<4,>=3.0.0 (from tox)
  Using cached https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting toml>=0.9.4 (from tox)
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting packaging>=14 (from tox)
  Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata<1,>=0.12; python_version < "3.8"->tox)
  Using cached https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging>=14->tox)
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting more-itertools (from zipp>=0.5->importlib-metadata<1,>=0.12; python_version < "3.8"->tox)
  Using cached https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl
Installing collected packages: more-itertools, zipp, importlib-metadata, pluggy, six, py, virtualenv, filelock, toml, pyparsing, packaging, tox, tox-venv, tox-pip-version
  Running setup.py install for tox-pip-version: started
    Running setup.py install for tox-pip-version: finished with status 'done'
Successfully installed filelock-3.0.12 importlib-metadata-0.23 more-itertools-7.2.0 packaging-19.2 pluggy-0.13.0 py-1.8.0 pyparsing-2.4.2 six-1.12.0 toml-0.10.0 tox-3.14.0 tox-pip-version-0.0.6 tox-venv-0.4.0 virtualenv-16.7.7 zipp-0.6.0
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 39e7959e003e
 ---> e49509275457
Step 5/6 : RUN echo "[tox]\nskipsdist = True\n[testenv]\ncommands = python -V\nskipinstall = True" > tox.ini
 ---> Running in 91bde1481ba4
Removing intermediate container 91bde1481ba4
 ---> 8ba0ee79f503
Step 6/6 : RUN tox-venv/bin/tox -e py27
 ---> Running in 01d6a2eb428e
py27 create: //.tox/py27
py27 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
py27 run-test-pre: PYTHONHASHSEED='2512785504'
py27 run-test: commands[0] | python -V
Python 2.7.15+
___________________________________ summary ____________________________________
  py27: commands succeeded
  congratulations :)
Removing intermediate container 01d6a2eb428e
 ---> a442ce71337b
Successfully built a442ce71337b
```

Thanks!
